version: '3'

tasks:
  menu:
    cmds:
      - echo "\n========= MENU ========="
      - echo "task install           - Instala o projeto Laravel"
      - echo "task create-project    - Cria novo projeto Laravel"
      - echo "task up                - Sobe containers"
      - echo "task down              - Remove containers (prod)"
      - echo "task down-v            - Remove containers e volumes"
      - echo "task restart           - Reinicia containers"
      - echo "task remake            - Destroi tudo e reinstala"
      - echo "task tinker            - Abre o Tinker"
      - echo "task test              - Roda os testes"
      - echo "task migrate           - Roda migrations"
      - echo "task fresh             - migrate:fresh --seed"
      - echo "task seed              - Executa os seeders"
      - echo "task cache             - Otimiza e gera caches"
      - echo "task cache-clear       - Limpa todos os caches"
      - echo "task ide-helper        - Gera arquivos de IDE"
      - echo "task pint              - Roda Laravel Pint"
      - echo "task pint-test         - Testa padrão Laravel Pint"
      - echo "task sql               - Acessa MySQL via terminal"
      - echo "task redis             - Acessa Redis via terminal"
      - echo "task app               - Entra no container da app"
      - echo "task db                - Entra no container do banco"
      - echo "task web               - Entra no container web"
      - echo "========================\n"

  for-linux-env:
    cmds:
      - echo "UID=$(id -u)" >> .env
      - echo "GID=$(id -g)" >> .env

  install:
    cmds:
      - task: build
      - task: up
      - docker compose exec app composer install
      - docker compose exec app cp .env.example .env
      - docker compose exec app php artisan key:generate
      - docker compose exec app php artisan storage:link
      - docker compose exec app chmod -R 777 storage bootstrap/cache
      - task: fresh

  create-project:
    cmds:
      - mkdir src
      - task: build
      - task: up
      - docker compose exec app composer create-project --prefer-dist laravel/laravel .
      - docker compose exec app php artisan key:generate
      - docker compose exec app php artisan storage:link
      - docker compose exec app chmod -R 777 storage bootstrap/cache
      - task: fresh

  build:
    cmds:
      - docker compose build

  up:
    cmds:
      - docker compose up --detach

  down:
    cmds:
      - docker compose -f compose.prod.yaml down --remove-orphans

  down-v:
    cmds:
      - docker compose down --remove-orphans --volumes

  stop:
    cmds:
      - docker compose stop

  restart:
    cmds:
      - task: down
      - task: up

  destroy:
    cmds:
      - docker compose down --rmi all --volumes --remove-orphans

  remake:
    cmds:
      - task: destroy
      - task: install

  ps:
    cmds:
      - docker compose ps

  web:
    cmds:
      - docker compose exec web bash

  app:
    cmds:
      - docker compose exec app bash

  tinker:
    cmds:
      - docker compose exec app php artisan tinker

  dump:
    cmds:
      - docker compose exec app php artisan dump-server

  test:
    cmds:
      - docker compose exec app php artisan test

  migrate:
    cmds:
      - docker compose exec app php artisan migrate

  fresh:
    cmds:
      - docker compose exec app php artisan migrate:fresh --seed

  seed:
    cmds:
      - docker compose exec app php artisan db:seed

  dacapo:
    cmds:
      - docker compose exec app php artisan dacapo

  rollback-test:
    cmds:
      - docker compose exec app php artisan migrate:fresh
      - docker compose exec app php artisan migrate:refresh

  optimize:
    cmds:
      - docker compose exec app php artisan optimize

  optimize-clear:
    cmds:
      - docker compose exec app php artisan optimize:clear

  cache:
    cmds:
      - docker compose exec app composer dump-autoload --optimize
      - docker compose exec app php artisan optimize
      - docker compose exec app php artisan event:cache
      - docker compose exec app php artisan view:cache

  cache-clear:
    cmds:
      - docker compose exec app composer clear-cache
      - docker compose exec app php artisan optimize:clear
      - docker compose exec app php artisan event:clear
      - docker compose exec app php artisan view:clear

  db:
    cmds:
      - docker compose exec db bash

  sql:
    cmds:
      - docker compose exec db bash -c 'mysql -u $$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE'

  redis:
    cmds:
      - docker compose exec redis redis-cli

  ide-helper:
    cmds:
      - docker compose exec app php artisan clear-compiled
      - docker compose exec app php artisan ide-helper:generate
      - docker compose exec app php artisan ide-helper:meta
      - docker compose exec app php artisan ide-helper:models --write --reset

  pint:
    cmds:
      - docker compose exec app ./vendor/bin/pint --verbose

  pint-test:
    cmds:
      - docker compose exec app ./vendor/bin/pint --verbose --test